require "alephant/harness/setup"
require_relative "env"

task :harness do

  config = {
    :tables   => [
      # Schema files are currently baked into the Alephant-Harness gem.
      # If you have custom schemas that don't fit the baked in schemas,
      # then you can inject their content dynamically, like so:
      # :schema > YAML::load_file("path/to/schema.yaml)
      { :name => ENV['LOOKUP_TABLE_NAME'], :schema    => "lookup" },
      { :name => ENV['SEQUENCER_TABLE_NAME'], :schema => "sequencer" }
    ],
    :queues   => [
      ENV['SQS_QUEUE_NAME']
    ]
  }

  Alephant::Harness::Setup.configure(config, ENV)
end
