require "alephant/harness/setup"
require_relative "env"

task :harness do

  config = {
    :tables   => [
      { :name => ENV['LOOKUP_TABLE_NAME'], :schema    => "lookup" },
      { :name => ENV['SEQUENCER_TABLE_NAME'], :schema => "sequencer" }
    ],
    :queues   => [
      ENV['SQS_QUEUE_NAME']
    ]
  }

  Alephant::Harness::Setup.configure(config, ENV)
end
