source "https://rubygems.org/"

group :production do
  gem "rack"
  gem "puma"
  gem "dotenv"
  gem "alephant-broker"
end

group :development do
  gem "spurious"
  gem "spurious-ruby-awssdk-helper"
  gem "alephant-harness"
  gem "pry"
end
