source "https://rubygems.org/"

group :production do
  gem "aws-sdk"
  gem "dotenv"
end

group :development do
  gem "spurious"
  gem "spurious-ruby-awssdk-helper"
  gem "alephant-harness"
  gem "pry"
end
