require "alephant/harness/setup"
require_relative "env"

task :harness do
  config = {
    :buckets => [ENV["S3_BUCKET"]],
    :queues  => [ENV["SQS_QUEUE"]]
  }

  Alephant::Harness::Setup.configure(config, ENV)
end

