source "https://rubygems.org/"

group :production do
  gem "aws-sdk"
  gem "dotenv"
  gem "alephant-renderer"
  gem "alephant-cache"
  gem "alephant-lookup"
  gem "alephant-sequencer"
end

group :development do
  gem "spurious"
  gem "spurious-ruby-awssdk-helper"
  gem "alephant-harness"
  gem "pry"
end
