$: << File.dirname(__FILE__)

require 'alephant/harness/setup'
require 'env'
require 'yaml'

task :harness do
  config = {
    :tables => [
      {
        :name   => ENV['DYNAMO_TABLE_NAME'],
        :schema => YAML.load_file(File.join('config', 'schema', 'renderer_locations.yaml'))
      }
    ]
  }
  Alephant::Harness::Setup.configure(config, ENV)

  Aws::DynamoDB::Client.new.put_item({
    :table_name => ENV['DYNAMO_TABLE_NAME'],
    :item => {
      'opts_hash' => {
        's' => '7e0c33c476b1089500d5f172102ec03e'
      },
      'location' => {
        's' => 'http://localhost:9393'
      }
    }
  })
end
